version: "3.9"

services:
  cloudsec:
    build: .

    image: dexter690990/cloudsec-cli:v1.0

    container_name: cloudsec-cli

    privileged: true

    network_mode: host

    stdin_open: true

    tty: true

    restart: "no"

    volumes:
      - .:/app
      - ./reports:/app/reports

      # Docker daemon
      - /var/run/docker.sock:/var/run/docker.sock

      # AWS Credentials
      - ~/.aws:/root/.aws:ro

      # Kubernetes
      - ~/.kube:/root/.kube:ro

      # Linux host inspection
      - /etc:/host/etc:ro
      - /var/log:/host/var/log:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro

    environment:
      AWS_DEFAULT_REGION: ap-south-1